name: Create Branch from issue

# issueがアサインされた時に実行
on:
  issues:
    types: [assigned]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create-branch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up a Git safe directory
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
      - uses: actions/checkout@v3
      - name: Empty commit
        run: |
          git config --global user.email "test@example.com"
          git config --global user.name "test"
          git commit --allow-empty -m "test"
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: healthybamboo/issue2branch@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
