name: Create Branch from issue
permissions: write-all
# issueがアサインされた時に実行
on:
  issues:
    types: [assigned]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create-branch:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up a Git safe directory
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
      - uses: actions/checkout@v3
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: healthybamboo/issue2branch@main
        id: iss2br
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
      - name: Comment on Issue with Branch Name
        run: |
          BRANCH_NAME=$(echo "${{ steps.iss2br.outputs.result }}")
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -d "{\"body\": \"Branch ${BRANCH_NAME} has been created.\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"
