name: Release
permissions: write-all
on:
  push:
    branches:
      - main    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
      - uses: actions/checkout@v3
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: healthybamboo/create_release_tag@fix/action
        id: create_tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release note
        uses: softprops/action-gh-release@v2
        with:
          tag_name:  ${{ steps.create_tag.outputs.tag }}
          draft: false
          generate_release_notes: true
          make_latest: true

